services:
  - type: web
    name: employee-attendance-tracker
    env: node
    buildCommand: node render-build.js
    startCommand: node render-start.js
    nodeVersion: 20
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: employee-attendance-db
          property: connectionString
      - key: FIREBASE_PROJECT_ID
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_STORAGE_BUCKET
        sync: false
      - key: FIREBASE_API_KEY
        sync: false
      - key: FIREBASE_AUTH_DOMAIN
        sync: false
      - key: FIREBASE_APP_ID
        sync: false

databases:
  - name: employee-attendance-db
    plan: free
    databaseName: employeeattendance
    ipAllowList: []